# Generated by Django 3.1.7 on 2021-03-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=220, unique=True)),
                ('short_url', models.CharField(max_length=7, unique=True)),
            ],
        ),
    ]
